<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Atlas.Core\Atlas.Core.csproj" />
  </ItemGroup>

  <Target Name="CopyPlugin" AfterTargets="Build">
    <MakeDir Directories="$(SolutionDir)Atlas.Api\bin\$(Configuration)\$(TargetFramework)\Plugins" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(SolutionDir)Atlas.Api\bin\$(Configuration)\$(TargetFramework)\Plugins" />
  </Target>

</Project>
